services:
  app:
    build: .
    environment:
      database_host: db
      database_name: java
      database_user: postgres
      database_password: postgres

      TELEGRAM_BOT_NAME: Pixzabot
      TELEGRAM_BOT_TOKEN: 7094226629:AAEeSbu36QHLZfeMIHOejOTdJdZ8O0MBME8
    ports:
      - "8080:8080"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=java
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"